ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: mnogo-losos-issuer
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: nft-stage.k8s.mnogo.losos
      paths:
      - path: "/"
  tls:
    - secretName: nft-inner-tls
      hosts:
      - nft-stage.k8s.mnogo.losos

ingressExternal:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kormikota-stage.mnogolososya.ru
      paths:
      - path: "/"
  tls:
  - secretName: kormikota-mnogolososya-ru-tls
    hosts:
    - kormikota-stage.mnogolososya.ru

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 500Mi
