[default]
MSK_TZ = 'Europe/Moscow'
CA_FILE_NAME = 'CA.pem'
NFT_CONVERSION_NOTIFICATION_NAME = 'NFTConversionStatusNotification'
LOGSTASH_HOST = 'logstash.mlkitchen.ai'
LOGSTASH_PORT = 12201
LOGGER_NAME = 'nft-backend-logger'
LOGGER_LEVEL = 'WARNING'
CONTRACT_ABI_FILE_NAME = 'KormiKotaNFT.json'
APP_NAME = 'ml.nft-app'
CHAIN_REORG_SAFETY_BLOCKS = 3
SCAN_DELAY = 5
MAX_SCAN_CHUNK_SIZE = 20
MIN_SCAN_CHUNK_SIZE = 3
MAX_REQUEST_RETRIES = 30
REQUEST_RETRY_SECONDS = 3.0
CHUNK_SIZE_DECREASE = 0.5
CHUNK_SIZE_INCREASE = 2.0
NFT_CATEGORY_MAP = {1 = 'common', 2 = 'epic', 3 = 'rare'}
CATEGORY_TOKEN_MAP = {1 = 1000, 2 = 800, 3 = 500}
STATIC_DIR = 'frontend'

[staging]
START_BLOCK = 21056510
CONTRACT_ADDRESS = '0xB233D617612C0ae70Fef347d22315c79996Ff507'
BLOCKCHAIN_ADDRESS = 'https://data-seed-prebsc-1-s1.binance.org:8545/'

[production]
START_BLOCK = 19724771
CONTRACT_ADDRESS = '0x18cbBe41E80474a8C91522689Cf8b97dd7FeDC06'
BLOCKCHAIN_ADDRESS = 'https://bsc-dataseed.binance.org/'
